# remote_theme: "jekyll/minima@1e8a445"
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: LVMM HPC cluster how to
description: Guia de uso del cluster HPC LVMM del CNyN
author: Aldo Gerardo Rodríguez Guerrero

repository:
  url: https://github.com/LVMMmx/lvmm
  path_to_book: ""
  branch: master
